// Herkenbare, eerlijke User-Agent. Vul CONTACT_URL desgewenst aan via env var
// SCRAPER_CONTACT (bv. een link naar dit project) — we zetten hier bewust geen
// persoonlijk e-mailadres in, want dat gaat naar servers van derden.
const CONTACT = process.env.SCRAPER_CONTACT || 'personal/educational project, no contact url set';

export const USER_AGENT_TOKEN = 'DeMoeilijksteKeusBot';
export const USER_AGENT = `Mozilla/5.0 (compatible; ${USER_AGENT_TOKEN}/0.1; ${CONTACT})`;

// `podiumpas` loopt mee als veld op elke gescrapete voorstelling (net als
// `naam`/`stad`), zodat de app kan filteren op Podiumpas-theaters zonder een
// aparte, makkelijk-te-vergeten lijst in de front-end bij te houden — vul
// 'm dus ook meteen in voor elk nieuw theater dat hier bijkomt.
export const THEATERS = [
  {
    id: 'delamar',
    naam: 'DeLaMar',
    stad: 'Amsterdam',
    baseUrl: 'https://delamar.nl',
    agendaUrl: 'https://delamar.nl/agenda/',
    podiumpas: true,
  },
  {
    id: 'bellevue',
    naam: 'Theater Bellevue',
    stad: 'Amsterdam',
    baseUrl: 'https://www.theaterbellevue.nl',
    agendaUrl: 'https://www.theaterbellevue.nl/agenda',
    podiumpas: true,
  },
  {
    id: 'meervaart',
    naam: 'Theater de Meervaart',
    stad: 'Amsterdam',
    baseUrl: 'https://meervaart.nl',
    agendaUrl: 'https://meervaart.nl/agenda',
    podiumpas: true,
  },
  {
    id: 'ita',
    naam: 'Internationaal Theater Amsterdam',
    stad: 'Amsterdam',
    baseUrl: 'https://ita.nl',
    agendaUrl: 'https://ita.nl/nl/agenda/',
    podiumpas: false,
  },
  {
    id: 'kleinekomedie',
    naam: 'De Kleine Komedie',
    stad: 'Amsterdam',
    baseUrl: 'https://www.dekleinekomedie.nl',
    agendaUrl: 'https://www.dekleinekomedie.nl/agenda',
    podiumpas: false,
  },
  {
    id: 'frascati',
    naam: 'Frascati',
    stad: 'Amsterdam',
    baseUrl: 'https://www.frascatitheater.nl',
    agendaUrl: 'https://www.frascatitheater.nl/nl/agenda',
    podiumpas: true,
  },
  {
    id: 'carre',
    naam: 'Koninklijk Theater Carré',
    stad: 'Amsterdam',
    baseUrl: 'https://carre.nl',
    agendaUrl: 'https://carre.nl/agenda',
    podiumpas: false,
  },
  {
    id: 'amstelveen',
    naam: 'Schouwburg Amstelveen',
    stad: 'Amstelveen',
    baseUrl: 'https://schouwburgamstelveen.nl',
    agendaUrl: 'https://schouwburgamstelveen.nl/nl/theater/agenda/',
    podiumpas: true,
  },
  {
    id: 'stadsschouwburgutrecht',
    naam: 'Stadsschouwburg Utrecht',
    stad: 'Utrecht',
    baseUrl: 'https://stadsschouwburg-utrecht.nl',
    agendaUrl: 'https://stadsschouwburg-utrecht.nl/agenda',
    podiumpas: true,
  },
  {
    id: 'theaterkikker',
    naam: 'Theater Kikker',
    stad: 'Utrecht',
    baseUrl: 'https://www.theaterkikker.nl',
    agendaUrl: 'https://www.theaterkikker.nl/agenda',
    podiumpas: true,
  },
  {
    id: 'krakeling',
    naam: 'Theater De Krakeling',
    stad: 'Amsterdam',
    baseUrl: 'https://krakeling.nl',
    agendaUrl: 'https://krakeling.nl/programma',
    podiumpas: true,
  },
  {
    id: 'mozaiek',
    naam: 'Podium Mozaïek',
    stad: 'Amsterdam',
    baseUrl: 'https://www.podiummozaiek.nl',
    agendaUrl: 'https://www.podiummozaiek.nl/programma/agenda',
    podiumpas: true,
  },
  {
    id: 'muziekgebouw',
    naam: "Muziekgebouw aan 't IJ",
    stad: 'Amsterdam',
    baseUrl: 'https://www.muziekgebouw.nl',
    agendaUrl: 'https://www.muziekgebouw.nl/nl/agenda',
    podiumpas: true,
  },
  {
    id: 'scala',
    naam: 'Scala Theater',
    stad: 'Amsterdam',
    baseUrl: 'https://www.scala-amsterdam.nl',
    agendaUrl: 'https://www.scala-amsterdam.nl/voorstellingen',
    podiumpas: true,
  },
  {
    id: 'omval',
    naam: 'Theater de Omval',
    stad: 'Diemen',
    baseUrl: 'https://www.theaterdeomval.nl',
    agendaUrl: 'https://www.theaterdeomval.nl/voorstellingen',
    podiumpas: true,
  },
  {
    id: 'delanding',
    naam: 'De Landing',
    stad: 'Amstelveen',
    baseUrl: 'https://schouwburgamstelveen.nl',
    agendaUrl: 'https://schouwburgamstelveen.nl/nl/delanding/agenda/',
    podiumpas: true,
  },
  {
    id: 'zaantheater',
    naam: 'Zaantheater',
    stad: 'Zaandam',
    baseUrl: 'https://zaantheater.nl',
    agendaUrl: 'https://zaantheater.nl/nl/theater/agenda/',
    podiumpas: true,
  },
  {
    id: 'bijlmerparktheater',
    naam: 'Bijlmer Parktheater',
    stad: 'Amsterdam',
    baseUrl: 'https://www.bijlmerparktheater.nl',
    agendaUrl: 'https://www.bijlmerparktheater.nl/agenda',
    podiumpas: true,
  },
  {
    id: 'ccamstel',
    naam: 'CC Amstel',
    stad: 'Amsterdam',
    baseUrl: 'https://ccamstel.nl',
    agendaUrl: 'https://ccamstel.nl/programma/',
    podiumpas: true,
  },
  {
    id: 'marionettentheater',
    naam: 'Amsterdams Marionetten Theater',
    stad: 'Amsterdam',
    baseUrl: 'https://www.marionettentheater.nl',
    agendaUrl: 'https://www.marionettentheater.nl/agenda/',
    podiumpas: true,
  },
  {
    id: 'griffioen',
    naam: 'VU Griffioen',
    stad: 'Amsterdam',
    baseUrl: 'https://griffioen.vu.nl',
    agendaUrl: 'https://griffioen.vu.nl/voorstellingen',
    podiumpas: true,
  },
  {
    id: 'pleintheater',
    naam: 'Plein Theater',
    stad: 'Amsterdam',
    baseUrl: 'https://plein-theater.nl',
    agendaUrl: 'https://plein-theater.nl/agenda',
    podiumpas: true,
  },
  {
    id: 'karavaan',
    naam: 'Karavaan - Theater de Drukkerij',
    stad: 'Alkmaar',
    baseUrl: 'https://www.karavaan.nl',
    agendaUrl: 'https://www.karavaan.nl/location/de-drukkerij/',
    podiumpas: true,
  },
  {
    id: 'schuur',
    naam: 'Schuur',
    stad: 'Haarlem',
    baseUrl: 'https://www.schuur.nl',
    agendaUrl: 'https://www.schuur.nl/agenda',
    podiumpas: true,
  },
  {
    id: 'bostheater',
    naam: 'Bostheater',
    stad: 'Amstelveen',
    baseUrl: 'https://bostheater.nl',
    agendaUrl: 'https://bostheater.nl/ons-programma/',
    podiumpas: true,
  },
  {
    id: 'hogewoerd',
    naam: 'Podium Hoge Woerd',
    stad: 'Utrecht',
    baseUrl: 'https://www.podiumhogewoerd.nl',
    agendaUrl: 'https://www.podiumhogewoerd.nl/agenda',
    podiumpas: true,
  },
  {
    id: 'flint',
    naam: 'Flint',
    stad: 'Amersfoort',
    baseUrl: 'https://flint.nl',
    agendaUrl: 'https://flint.nl/agenda/',
    podiumpas: true,
  },
  {
    id: 'aandeslinger',
    naam: 'Aan de Slinger',
    stad: 'Houten',
    baseUrl: 'https://www.aandeslinger.nl',
    agendaUrl: 'https://www.aandeslinger.nl/programma',
    podiumpas: true,
  },
  {
    id: 'corrosia',
    naam: 'Corrosia',
    stad: 'Almere',
    baseUrl: 'https://www.corrosia.nl',
    agendaUrl: 'https://www.corrosia.nl/agenda/programma',
    podiumpas: true,
  },
  {
    id: 'kunstlinie',
    naam: 'Kunstlinie',
    stad: 'Almere',
    baseUrl: 'https://kunstlinie.nl',
    agendaUrl: 'https://kunstlinie.nl/programma/',
    podiumpas: true,
  },
];
